sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=3.0.0

sonar.sources=.
sonar.exclusions=tests/**,**/__pycache__/**,*.cfg,*.ini,k8s/**

sonar.tests=tests
sonar.test.inclusions=tests/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
